server:
  port: 8761

#app:
#  id: lptest
#apollo:
#  meta: http://192.168.24.132:8080
#  bootstrap:
#    enabled: true
#    eagerLoad:
#      enabled: true

spring:
  datasource:
    jdbc-url: jdbc:mysql://47.99.137.184:3306/testDatabase?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Lu954439.
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource1:
    jdbc-url: jdbc:mysql://47.99.137.184:3306/testDatabase?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Lu954439.
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.24.134
    port: 5672
    username: rabbitmq
    password: 123456
    #虚拟host 可以不设置,使用server默认host
    virtual-host: /pandm
    # 发送者开启 return 确认机制
    publisher-returns: true
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual #设置确认模式手工确认
        prefetch: 1 # 每个消费者每次可以消费一个
#        concurrency: 3 #消费者最小数量
#        max-concurrency: 10 # 消费者最大数量

mybatis:
  mapper-locations: classpath:/mapper/*Dao.xml
  typeAliasesPackage: online.pandm.demo.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl