server:
  port: 8080

spring:
  datasource:
    jdbc-url: jdbc:mysql://47.99.137.184:3306/testDatabase?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Lu954439.
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource1:
    jdbc-url: jdbc:mysql://47.99.137.184:3306/testDatabase?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Lu954439.
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:/mapper/*Dao.xml
  typeAliasesPackage: online.pandm.demo.entity